// flow-typed signature: 847707984772af9a80f9e05414ae651a
// flow-typed version: <<STUB>>/bootstrap_v4.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare module 'bootstrap/dist/css/bootstrap.min.css' {
  declare module.exports: $Exports<'bootstrap/dist/css/bootstrap.min.css'>;
}

